<h1 style="text-align:center"><b>[Step 1]</b></h1>
<h2 style="text-align:center"><b>Simple Cleaning Data Process</b></h2>
<p style="text-align:center">Removing URL & HTML Parsing</p>

In [16]:
import pandas as pd
import re
import time

from tqdm import tqdm

In [17]:
df = pd.read_csv("../0_SCRAPING/IndoECommerce.csv")
print("Original shape:", df.shape)
df.head()

Original shape: (10559, 3)

                                              Ulasan  Rating  Membantu
0  Barang pesanan datang sesuai jadwal \nBarang p...       5         0
1  Bahan: Bagus\nManfaat produk: Sangat baik\nJen...       5         0
2  Bahan: bagus\nManfaat produk: mencerahkan\nJen...       5         1
3  Bahan: Sesuai pemesanan\nManfaat produk: Mence...       5         0
4  Bahan: Bagus sdah berlangganan\nManfaat produk...       5         0

In [18]:
df = df.dropna(subset=["Ulasan"]).copy() # Drop NA
df = df[df["Ulasan"].astype(str).str.strip() != ''] # Remove empty string
df = df.drop_duplicates(subset=["Ulasan"], keep='first') # Remove duplicates

In [19]:
url_pattern = re.compile(r'https?://\S+|www\.\S+')
html_pattern = re.compile(r'<.*?>')
underscore_pattern = re.compile(r'_')
space_pattern = re.compile(r'\s+')


def text_cleaner(text):

    text = str(text).lower()

    text = url_pattern.sub('', text)
    text = html_pattern.sub('', text)
    text = underscore_pattern.sub('', text)
    text = space_pattern.sub(' ', text).strip()

    return text

In [21]:
df['ulasan_cleaned'] = df['Ulasan'].apply(text_cleaner)
print(f'Raw text:\n{df.Ulasan.iloc[1]}\nClean text:\n{df.ulasan_cleaned.iloc[1]}')

Raw text:
Bahan: Bagus
Manfaat produk: Sangat baik
Jenis kulit: All skin
Clean text:
bahan: bagus manfaat produk: sangat baik jenis kulit: all skin

In [22]:
print("After clean shape:", df.shape)
df.head()

After clean shape: (7875, 5)

,Ulasan,Rating,Membantu,emoji_count,ulasan_cleaned
0,Barang pesanan datang sesuai jadwal \nBarang p...,5,0,0,barang pesanan datang sesuai jadwal barang pes...
1,Bahan: Bagus\nManfaat produk: Sangat baik\nJen...,5,0,0,bahan: bagus manfaat produk: sangat baik jenis...
2,Bahan: bagus\nManfaat produk: mencerahkan\nJen...,5,1,0,bahan: bagus manfaat produk: mencerahkan jenis...
3,Bahan: Sesuai pemesanan\nManfaat produk: Mence...,5,0,0,bahan: sesuai pemesanan manfaat produk: mencer...
4,Bahan: Bagus sdah berlangganan\nManfaat produk...,5,0,0,bahan: bagus sdah berlangganan manfaat produk:...

In [23]:
print("📤 Exporting data to CSV...")

pbar = tqdm(total=1, desc="Exporting", leave=True)
df_export = df[['ulasan_cleaned', 'Rating', 'Membantu']]
df_export.to_csv('simple_clean.csv', index=False)
pbar.update(1)
pbar.close()

print(f"✅ Successfully exported {len(df_export)} rows to 'simple_clean.csv'")

📤 Exporting data to CSV...

Exporting: 100%|██████████| 1/1 [00:00<00:00, 26.69it/s]

✅ Successfully exported 7875 rows to 'simple_clean.csv'